spring.application.name=ticketsystem-backend

server.port=8080

#database settings
spring.datasource.username=admin
spring.datasource.password=tiendalibre2025
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_system?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#jwt
jwt.secret.key=HxJgY5NEtXnSMrOvJRepBfBWRCL4LYa+baO9sX+4+cHFGVZPOGFzvRZfyXz+5Vuvbz3rbZBAmmS5rQ/E1sWXuAJYMiHBAtN3P+mcartt+Ho=
jwt.secret.key.refresh=i2HldKzv1FPq3tEBoJ3Z7oE/7YHaRQa/IcJbjQnFjjxo1/A2eStUyHkbNffKxpA2ohU88WY/m6XCFcRZiJ6uxg+n3Rn40ECW5i/burmvXBc=

# access token: 15 min
jwt.expiration.time=900000

# refresh token: 30 dias
jwt.refresh.expiration=2592000000